name: Move Tmp Files to Data

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

    - name: Checkout main branch
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Move files
      run: |
        python move.py

    - name: Commit changes
      id: asset-auto-commit-action
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Move tmp files to data"
